# Generated by Django 5.2.8 on 2025-11-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_options_alter_comment_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='file',
            new_name='image',
        ),
    ]
