# Generated by Django 5.2.8 on 2025-11-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='todos/')),
                ('status', models.CharField(max_length=50)),
                ('start_data', models.DateTimeField()),
                ('finish_data', models.DateTimeField()),
            ],
        ),
    ]
